# Generated by Django 3.2.18 on 2023-05-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('SENT', 'SENT'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], max_length=64),
        ),
    ]
