# Generated by Django 3.2.18 on 2023-04-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_variant_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='models.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_banners', to='models.file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_photos', to='models.file'),
        ),
    ]
