# Generated by Django 3.2.18 on 2023-04-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20230429_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='born_date',
        ),
    ]
