# Generated by Django 3.2.18 on 2023-05-26 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20230525_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='seller',
        ),
        migrations.AddField(
            model_name='shipping',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_shippings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.TextField(blank=True),
        ),
    ]
