# Generated by Django 3.2.18 on 2023-06-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20230525_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
