# Generated by Django 3.2.18 on 2023-05-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('NS', 'NS'), ('AGUASCALIENTES', 'AGUASCALIENTES'), ('BAJA CALIFORNIA', 'BAJA CALIFORNIA'), ('BAJA CALIFORNIA SUR', 'BAJA CALIFORNIA SUR'), ('CAMPECHE', 'CAMPECHE'), ('COAHUILA', 'COAHUILA'), ('COLIMA', 'COLIMA'), ('CHIAPAS', 'CHIAPAS'), ('CHIHUAHUA', 'CHIHUAHUA'), ('DURANGO', 'DURANGO'), ('CIUDAD DE MEXICO', 'CIUDAD DE MEXICO'), ('GUANAJUATO', 'GUANAJUATO'), ('GUERRERO', 'GUERRERO'), ('HIDALGO', 'HIDALGO'), ('JALISCO', 'JALISCO'), ('MEXICO', 'MEXICO'), ('MICHOACAN', 'MICHOACAN'), ('MORELOS', 'MORELOS'), ('NAYARIT', 'NAYARIT'), ('NUEVO LEON', 'NUEVO LEON'), ('OAXACA', 'OAXACA'), ('PUEBLA', 'PUEBLA'), ('QUERETARO', 'QUERETARO'), ('QUINTANA ROO', 'QUINTANA ROO'), ('SAN LUIS POTOSI', 'SAN LUIS POTOSI'), ('SINALOA', 'SINALOA'), ('SONORA', 'SONORA'), ('TABASCO', 'TABASCO'), ('TAMAULIPAS', 'TAMAULIPAS'), ('TLAXCALA', 'TLAXCALA'), ('VERACRUZ', 'VERACRUZ'), ('YUCATAN', 'YUCATAN'), ('ZACATECAS', 'ZACATECAS')], max_length=64),
        ),
    ]
