# Generated by Django 3.2.18 on 2023-05-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
