# Generated by Django 3.2.18 on 2023-06-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shipping',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
