### __Seed builder__
#   Autogenerated commands
#   Add custom commands at the end

FROM python:3.8.10-alpine
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1
RUN pip install --upgrade pip==23.0.1
RUN apk update && apk add gcc postgresql-dev postgresql-client python3-dev musl-dev openssh-client libffi-dev tzdata
ENV TZ=America/Mexico_City

# __End autogenerated__
# Include commands after this block
###

COPY requirements.txt .
COPY seed/requirements.txt seed/
RUN apk update && apk add cmake make g++ libstdc++ libgcc libuv-dev openssl-dev gfortran openblas-dev libgfortran libgomp lapack-dev meson ninja libc-dev linux-headers cython
# RUN apk add py3-numpy py3-pandas libressl-dev libxml2 libxml2-dev libxslt libxslt-dev libjpeg-turbo-dev zlib-dev
RUN pip install cython
RUN pip install numpy==1.17.4
RUN pip install pandas==0.25.3
RUN pip install -r requirements.txt
COPY . .